### ISSUE TITLE
[CI] Publish step randomly fails

### ISSUE THREAD

**Issue by kikmon** [jbrandwood/huc#19]
The 'Publish Package' step run at the end of the flow seems to be randomly failing, with errors pointing to github infra issues (need logs)

The action 'pyTooling/Actions/releaser' doesn't seem to have any retry mechanism.
See if retries can be added to the action, on if they can be implemented at a higher level, in the yaml file itself using other actions

**Comment by jbrandwood** [comment]
Thanks again! Yep, it's scary to get the email from github saying that the build failed, and then to find out that it was just a glitch in uploading packages to github itself is a kinda annoying.

**Comment by jbrandwood** [comment]
Not your fault BTW ... but I'm sure that you can figure out how to fix it!

Best wishes,

John

**Comment by kikmon** [comment]
My bad for trusting the infra :)

**Comment by kikmon** [comment]
Managed to get some logs in my fork

Run pyTooling/Actions/releaser@r0
/usr/bin/docker run --name ghcriopytoolingreleaser_3c2065 --label 08450d --workdir /github/workspace --rm -e MSYS2_INSTALL_FOLDER -e INPUT_TOKEN -e INPUT_TAG -e INPUT_RM -e INPUT_FILES -e INPUT_SNAPSHOTS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/huc/huc":"/github/workspace" ghcr.io/pytooling/releaser
· Get list of artifacts to be uploaded
  glob(*.zip):
  - huc-2022-05-31-Darwin.zip
  - huc-2022-05-31-Win64.zip
  - huc-2022-05-31-Linux.zip
· Check SemVer compliance of the reference/tag
· Get GitHub API handler (authenticate)
· Get Repository handler
· Get Release handler
· RM set. All previous assets are being cleared...
 - huc-2022-05-30-Darwin.zip
 - huc-2022-05-30-Linux.zip
 - huc-2022-05-30-Win64.zip
Post "https://uploads.github.com/repos/kikmon/huc/releases/67601582/assets?label=&name=huc-2022-05-31-Darwin.zip": http2: client connection force closed via ClientConn.Close
Traceback (most recent call last):
  File "/releaser.py", line 187, in <module>
    check_call(cmd, env=env)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gh', 'release', 'upload', '--repo', 'kikmon/huc', '--clobber', 'master', 'huc-2022-05-31-Darwin.zip', 'huc-2022-05-31-Win64.zip', 'huc-2022-05-31-Linux.zip']' returned non-zero exit status 1.
· Cleanup and/or upload artifacts
 > gh release upload --repo kikmon/huc --clobber master huc-2022-05-31-Darwin.zip huc-2022-05-31-Win64.zip huc-2022-05-31-Linux.zip

**Comment by kikmon** [comment]
Issue reported and acknowledged in the releaser action repo 
https://github.com/pyTooling/Actions/issues/48
Let see how this unfolds.
